export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const STORE_SEARCH_PARAMS = 'STORE_SEARCH_PARAMS';
export const GET_FLIGHT_DETAILS = 'GET_FLIGHT_DETAILS';
export const USER_LOGIN ='USER_LOGIN';
export const USER_SIGNUP ='USER_SIGNUP';

