export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';

export const CUSTOMER_SIGNUP_SUCCESS = 'CUSTOMER_SIGNUP_SUCCESS';
export const CUSTOMER_SIGNUP_FAILURE = 'CUSTOMER_SIGNUP_FAILURE';
export const RESTAURANT_SIGNUP_SUCCESS = 'RESTAURANT_SIGNUP_SUCCESS';
export const RESTAURANT_SIGNUP_FAILURE = 'RESTAURANT_SIGNUP_FAILURE';

export const RESTAURANT_LOGIN_SUCCESS = 'RESTAURANT_LOGIN_SUCCESS';
export const RESTAURANT_LOGIN_FAILURE = 'RESTAURANT_LOGIN_FAILURE';
export const CUSTOMER_LOGIN_SUCCESS = 'CUSTOMER_LOGIN_SUCCESS';
export const CUSTOMER_LOGIN_FAILURE = 'CUSTOMER_LOGIN_FAILURE';

export const UPDATE_RESTAURANT_SUCCESS = 'UPDATE_RESTAURANT_SUCCESS';
export const UPDATE_RESTAURANT_FAILURE = 'UPDATE_RESTAURANT_FAILURE';

export const GET_RESTAURANT_MENU = 'GET_RESTAURANT_MENU';
export const ADD_RESTAURANT_MENU = 'ADD_RESTAURANT_MENU';
export const EDIT_RESTAURANT_MENU = 'EDIT_RESTAURANT_MENU';

export const GET_RESTAURANT_ORDERS = 'GET_RESTAURANT_ORDERS';
export const UPDATE_ORDER_STATUS = 'UPDATE_ORDER_STATUS';

export const GET_ALL_RESTAURANTS = 'GET_ALL_RESTAURANTS';
export const GET_ALL_RESTAURANT_MENU = 'GET_ALL_RESTAURANT_MENU';

export const SET_SEARCH_STRING = 'SET_SEARCH_STRING';
export const SET_FAVORITE = 'SET_FAVORITE';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

export const UPDATE_CUSTOMER_SUCCESS = 'UPDATE_CUSTOMER_SUCCESS';

export const GET_ADDRESS = 'GET_ADDRESS';
export const ADD_ADDRESS = 'ADD_ADDRESS';

export const CLEAR_CART = 'CLEAR_CART';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
